fix debug print of pointer types
rust-lang/chalk pull request #608
Opened 2020-09-12 13:55 UTC by Areredify

Fixes a confusing debug print of pointer types, previously `&'a T` it was printed as `Not<!0_0, T>` and `*const T` was printed as `Not<T>`, which was somewhat confusing.

2020-09-12 13:58 UTC, Areredify commented
While we are at it, is there a specific reason for application types to be printed as ugly as they are now, or I can go ahead and change them to be rendered "properly"?

2020-09-12 14:40 UTC, detrumi requested changes
I think we should add a `impl Debug for Mutability` instead, to avoid doing this for each place where it can occur.

> While we are at it, is there a specific reason for application types to be printed as ugly as they are now, or I can go ahead and change them to be rendered "properly"?

I'm assuming it's there because implementing Debug directly doesn't work, but if we don't need it then feel free to simplify it.

2020-09-12 14:51 UTC, Areredify commented
>I think we should add a impl Debug for Mutability
I am not sure how to do that, it renders to different things when in different places, i.e. `Mutability::Not` in `Ref` renders to `{{&}}` and to `{{*const}}` in `RawPtr`.

By ugly I didn't mean the implementation, I meant that printed types are in `{type name}{substitution}` format, instead of the natural way to render it, i.e. `{{array}}<u32, 3>` instead of `[u32; 3]`.

2020-09-14 19:06 UTC, detrumi commented
Ah right, did not notice that.
And yeah, improving the application ty formatting would be great

2020-09-14 19:06 UTC, detrumi approved these changes

2020-09-14 21:38 UTC, jackh726 commented
So, yeah, debug printing of `Application` tys could be improved (see the [changes](https://github.com/rust-lang/rust/blob/bb0067c75ea82efa8a09213bfba0dc2583ac0a4c/compiler/rustc_middle/src/traits/chalk.rs#L105) I made in the rustc integration). The only problem is this can't be done *generically*, since it relies on unpacking the substitution *without* having access to an `interner` instance. But we can easily do this for the `chalk-integration` `Interner` impl.

2020-09-14 21:39 UTC, jackh726 commented
@Areredify feel free to followup with this, if you want. Or just file an issue for someone else to followup.

In the meantime: @bors r=jackh726,detrumi

2020-09-14 21:45 UTC, merged