Add TypeFlags for TyKind in chalk-ir
rust-lang/chalk pull request #639
Opened 2020-10-29 01:48 UTC by chfont

Handles #627

2020-10-29 22:31 UTC, matthewjasper commented on chalk-ir/src/lib.rs
> +            TypeFlags::HAS_TY_OPAQUE | compute_substitution_flags(substitution, interner)
So, looking through how this is used in rustc  I think that the majority of code would not expect this it to be set for `TyKind::OpaqueType`, only `AliasTy::Opaque`.

2020-11-01 22:00 UTC, jackh726 requested changes
My comments can apply to the rest of the tests I didn't comment on

2020-11-01 22:00 UTC, jackh726 commented on tests/test/type_flags.rs
> +    );
As above, can we use the `ty` macro?

2020-12-09 21:20 UTC, jackh726 commented on tests/test/type_flags.rs
> +use chalk_integration::{empty_substitution, lifetime, ty};
This can be moved later.

2020-12-09 21:21 UTC, jackh726 commented on tests/test/type_flags.rs
> +                    value: chalk_ir::ConstValue::InferenceVar(chalk_ir::InferenceVar::from(0)),
oh this is const, nvm

2020-12-09 21:22 UTC, jackh726 commented
@matthewjasper can you take another look at this? I've rebased and updated per your review.

2020-12-11 21:18 UTC, matthewjasper reviewed
r=me with comment addressed

2020-12-11 21:39 UTC, jackh726 commented
@bors r=matthewjasper

2020-12-11 21:46 UTC, merged